### ISSUE TITLE
您好 请问无法运行，是需要配置域名吗

### ISSUE THREAD

**Issue by wangguangzhong** [chudaozhe/enterprise-admin#1]
[](![搜狗截图20230206180457]([](https://user-images.githubusercontent.com/28469601/216943511-4be78102-1583-4052-87c2-65bb9455b79c.png)))

**Comment by wangguangzhong** [comment]
Access to XMLHttpRequest at 'http://localhost/v1/admin/login' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js?b50d:187          POST http://localhost/v1/admin/login net::ERR_FAILED 404 (Not Found)
dispatchXhrRequest @ xhr.js?b50d:187
xhrAdapter @ xhr.js?b50d:13
dispatchRequest @ dispatchRequest.js?5270:53
Promise.then（异步）
request @ Axios.js?0a06:88
wrap @ bind.js?1d2b:9
post @ axios.js?8116:61
doLogin @ user.js?ffc5:10
login @ login.vue?8d26:60
eval @ login.vue?8d26:79
eval @ element-ui.common.js?5c96:23207
eval @ element-ui.common.js?5c96:23730
complete @ index.js?a15e:89
eval @ index.js?a15e:225
next @ util.js?fa49:148
next @ util.js?fa49:116
cb @ index.js?a15e:173
validatePassword @ login.vue?8d26:40
eval @ index.js?a15e:216
next @ util.js?fa49:114
asyncSerialArray @ util.js?fa49:120
eval @ util.js?fa49:154
asyncMap @ util.js?fa49:151
validate @ index.js?a15e:141
validate @ element-ui.common.js?5c96:23726
eval @ element-ui.common.js?5c96:23201
validate @ element-ui.common.js?5c96:23200
submitForm @ login.vue?8d26:77
click @ login.vue?1954:89
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
invoker @ vue.runtime.esm.js?2b0e:1815
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
Vue.$emit @ vue.runtime.esm.js?2b0e:3716
handleClick @ element-ui.common.js?5c96:9463
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
invoker @ vue.runtime.esm.js?2b0e:1815
original_1._wrapper @ vue.runtime.esm.js?2b0e:7473
:8080/#/article:1 Access to XMLHttpRequest at 'http://localhost/v1/admin/undefined/category/0/article?keyword=&page=1&max=10' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js?b50d:187          GET http://localhost/v1/admin/undefined/category/0/article?keyword=&page=1&max=10 net::ERR_FAILED 404 (Not Found)
dispatchXhrRequest @ xhr.js?b50d:187
xhrAdapter @ xhr.js?b50d:13
dispatchRequest @ dispatchRequest.js?5270:53
Promise.then（异步）
request @ Axios.js?0a06:88
wrap @ bind.js?1d2b:9
get @ axios.js?8116:52
gets @ article.js?4bc3:14
listByArticle @ index.vue?6ced:128
mounted @ index.vue?6ced:120
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
callHook$1 @ vue.runtime.esm.js?2b0e:4031
insert @ vue.runtime.esm.js?2b0e:4423
invokeInsertHook @ vue.runtime.esm.js?2b0e:6942
patch @ vue.runtime.esm.js?2b0e:7153
Vue._update @ vue.runtime.esm.js?2b0e:3769
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher.run @ vue.runtime.esm.js?2b0e:3522
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4121
eval @ vue.runtime.esm.js?2b0e:3143
flushCallbacks @ vue.runtime.esm.js?2b0e:3065
Promise.then（异步）
timerFunc @ vue.runtime.esm.js?2b0e:3090
nextTick @ vue.runtime.esm.js?2b0e:3155
queueWatcher @ vue.runtime.esm.js?2b0e:4207
Watcher.update @ vue.runtime.esm.js?2b0e:3513
Vue.$forceUpdate @ vue.runtime.esm.js?2b0e:3794
eval @ vue.runtime.esm.js?2b0e:8574
wrappedHook @ vue.runtime.esm.js?2b0e:1860
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
invoker @ vue.runtime.esm.js?2b0e:1810
eval @ vue.runtime.esm.js?2b0e:8125
eval @ vue.runtime.esm.js?2b0e:305
end @ vue.runtime.esm.js?2b0e:7899
onEnd @ vue.runtime.esm.js?2b0e:7904
localhostundefined/:1          GET http://localhostundefined/ 503 (Service Unavailable)
Image（异步）
baseSetAttr @ vue.runtime.esm.js?2b0e:7372
setAttr @ vue.runtime.esm.js?2b0e:7346
updateAttrs @ vue.runtime.esm.js?2b0e:7297
invokeCreateHooks @ vue.runtime.esm.js?2b0e:6655
createElm @ vue.runtime.esm.js?2b0e:6546
createChildren @ vue.runtime.esm.js?2b0e:6640
createElm @ vue.runtime.esm.js?2b0e:6544
createChildren @ vue.runtime.esm.js?2b0e:6640
createElm @ vue.runtime.esm.js?2b0e:6544
patch @ vue.runtime.esm.js?2b0e:7071
Vue._update @ vue.runtime.esm.js?2b0e:3765
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher @ vue.runtime.esm.js?2b0e:3436
mountComponent @ vue.runtime.esm.js?2b0e:3892
Vue.$mount @ vue.runtime.esm.js?2b0e:8772
init @ vue.runtime.esm.js?2b0e:4407
createComponent @ vue.runtime.esm.js?2b0e:6567
createElm @ vue.runtime.esm.js?2b0e:6521
createChildren @ vue.runtime.esm.js?2b0e:6640
createElm @ vue.runtime.esm.js?2b0e:6544
patch @ vue.runtime.esm.js?2b0e:7071
Vue._update @ vue.runtime.esm.js?2b0e:3765
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher @ vue.runtime.esm.js?2b0e:3436
mountComponent @ vue.runtime.esm.js?2b0e:3892
Vue.$mount @ vue.runtime.esm.js?2b0e:8772
init @ vue.runtime.esm.js?2b0e:4407
createComponent @ vue.runtime.esm.js?2b0e:6567
createElm @ vue.runtime.esm.js?2b0e:6521
createChildren @ vue.runtime.esm.js?2b0e:6640
createElm @ vue.runtime.esm.js?2b0e:6544
patch @ vue.runtime.esm.js?2b0e:7071
Vue._update @ vue.runtime.esm.js?2b0e:3765
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher @ vue.runtime.esm.js?2b0e:3436
mountComponent @ vue.runtime.esm.js?2b0e:3892
Vue.$mount @ vue.runtime.esm.js?2b0e:8772
init @ vue.runtime.esm.js?2b0e:4407
createComponent @ vue.runtime.esm.js?2b0e:6567
createElm @ vue.runtime.esm.js?2b0e:6521
createChildren @ vue.runtime.esm.js?2b0e:6640
createElm @ vue.runtime.esm.js?2b0e:6544
patch @ vue.runtime.esm.js?2b0e:7071
Vue._update @ vue.runtime.esm.js?2b0e:3765
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher @ vue.runtime.esm.js?2b0e:3436
mountComponent @ vue.runtime.esm.js?2b0e:3892
Vue.$mount @ vue.runtime.esm.js?2b0e:8772
init @ vue.runtime.esm.js?2b0e:4407
createComponent @ vue.runtime.esm.js?2b0e:6567
createElm @ vue.runtime.esm.js?2b0e:6521
patch @ vue.runtime.esm.js?2b0e:7071
Vue._update @ vue.runtime.esm.js?2b0e:3765
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher @ vue.runtime.esm.js?2b0e:3436
mountComponent @ vue.runtime.esm.js?2b0e:3892
Vue.$mount @ vue.runtime.esm.js?2b0e:8772
init @ vue.runtime.esm.js?2b0e:4407
merged @ vue.runtime.esm.js?2b0e:4561
createComponent @ vue.runtime.esm.js?2b0e:6567
createElm @ vue.runtime.esm.js?2b0e:6521
patch @ vue.runtime.esm.js?2b0e:7109
Vue._update @ vue.runtime.esm.js?2b0e:3769
updateComponent @ vue.runtime.esm.js?2b0e:3875
Watcher.get @ vue.runtime.esm.js?2b0e:3446
Watcher.run @ vue.runtime.esm.js?2b0e:3522
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4121
eval @ vue.runtime.esm.js?2b0e:3143
flushCallbacks @ vue.runtime.esm.js?2b0e:3065
Promise.then（异步）
timerFunc @ vue.runtime.esm.js?2b0e:3090
nextTick @ vue.runtime.esm.js?2b0e:3155
queueWatcher @ vue.runtime.esm.js?2b0e:4207
Watcher.update @ vue.runtime.esm.js?2b0e:3513
Vue.$forceUpdate @ vue.runtime.esm.js?2b0e:3794
eval @ vue.runtime.esm.js?2b0e:8574
wrappedHook @ vue.runtime.esm.js?2b0e:1860
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:3017
invoker @ vue.runtime.esm.js?2b0e:1810
eval @ vue.runtime.esm.js?2b0e:8125
eval @ vue.runtime.esm.js?2b0e:305
end @ vue.runtime.esm.js?2b0e:7899
onEnd @ vue.runtime.esm.js?2b0e:7904
:8080/#/article:1 Access to XMLHttpRequest at 'http://localhost/v1/admin/undefined/category2' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
vue.runtime.esm.js?2b0e:4605 [Vue warn]: Invalid prop: type check failed for prop "options". Expected Array, got Object

**Comment by chudaozhe** [comment]
不配域名也可以运行，具体可以参考这个视频：https://www.bilibili.com/video/BV17T411K7jM
