### ISSUE TITLE
关于文件配置修改的问题

### ISSUE THREAD

**Issue by mucstudio** [chudaozhe/enterprise-admin#2]
`let _host = null;
const host = function(){
	if(_host) return _host;
	let ln = window.location;
	//ent.cw.net
	//http://localhost:7097
	return ln.href.indexOf("localhost") > 0 ? 'http://localhost' : "https://ent.cuiwei.net";
};
global.host = host();`

非常喜欢这个程序，但是有个问题不太明白，请问一下
	`//ent.cw.net
	//http://localhost:7097
	return ln.href.indexOf("localhost") > 0 ? 'http://localhost' : "https://ent.cuiwei.net";`
	
	
	这三处域名对应的应该填写的都是代表了那一个地方的呢？

**Comment by chudaozhe** [comment]
这里配的是接口的前缀，区分了本地环境（ http://localhost ）和线上环境（ https://ent.cuiwei.net ）。
